name: Build Android APK

on:
  push:
    branches:
      - main  # Adjust as necessary
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use JDK 11
          distribution: 'adopt'

      - name: Install Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -L -o commandlinetools.zip "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip"
          unzip commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest

      - name: Set up Android SDK
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-31"

      - name: Create Android Project
        run: |
          mkdir -p $GITHUB_WORKSPACE/LLMChatApp/app/src/main/java/com/example/llmchatapp
          mkdir -p $GITHUB_WORKSPACE/LLMChatApp/app/src/main/res/layout
          mkdir -p $GITHUB_WORKSPACE/LLMChatApp/app/src/main/res/values
          mkdir -p $GITHUB_WORKSPACE/LLMChatApp/app

          # Create build.gradle file
          echo "plugins { id 'com.android.application' }" > $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "android {" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "    compileSdk 31" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "    defaultConfig {" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "        applicationId \"com.example.llmchatapp\"" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "        minSdk 21" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "        targetSdk 31" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "        versionCode 1" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "        versionName \"1.0\"" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "    }" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "    buildTypes {" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "        release {" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "            minifyEnabled false" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "        }" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "    }" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "}" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "dependencies {" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "    implementation 'com.google.android.material:material:1.8.0'" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "    implementation 'com.squareup.retrofit2:retrofit:2.9.0'" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "    implementation 'org.nanohttpd:nanohttpd:2.3.1'" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle
          echo "}" >> $GITHUB_WORKSPACE/LLMChatApp/app/build.gradle

          # Create AndroidManifest.xml
          cat <<EOF > $GITHUB_WORKSPACE/LLMChatApp/app/src/main/AndroidManifest.xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.llmchatapp">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.MaterialComponents.DayNight.DarkActionBar">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".SettingsActivity" />
    </application>
</manifest>
EOF

          # Create MainActivity.kt
          cat <<EOF > $GITHUB_WORKSPACE/LLMChatApp/app/src/main/java/com/example/llmchatapp/MainActivity.kt
package com.example.llmchatapp

import android.content.Intent
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import fi.iki.elonen.nanonetwork.NanoHTTPD

class MainActivity : AppCompatActivity() {
    private lateinit var localHttpServer: LocalHttpServer
    private lateinit var messageInput: EditText
    private lateinit var sendButton: Button
    private lateinit var chatOutput: TextView
    private lateinit var settingsButton: Button

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        messageInput = findViewById(R.id.messageInput)
        sendButton = findViewById(R.id.sendButton)
        chatOutput = findViewById(R.id.chatOutput)
        settingsButton = findViewById(R.id.settingsButton)

        localHttpServer = LocalHttpServer(5000)
        localHttpServer.start()

        sendButton.setOnClickListener {
            val message = messageInput.text.toString()
            sendMessageToServer(message)
        }

        settingsButton.setOnClickListener {
            startActivity(Intent(this, SettingsActivity::class.java))
        }
    }

    private fun sendMessageToServer(message: String) {
        // Logic to send messages to the server
    }

    override fun onDestroy() {
        super.onDestroy()
        localHttpServer.stop()
    }
}
EOF

          # Create LocalHttpServer.kt
          cat <<EOF > $GITHUB_WORKSPACE/LLMChatApp/app/src/main/java/com/example/llmchatapp/LocalHttpServer.kt
package com.example.llmchatapp

import fi.iki.elonen.nanonetwork.NanoHTTPD

class LocalHttpServer(port: Int) : NanoHTTPD(port) {
    override fun serve(session: IHTTPSession): Response {
        val userInput = session.parameters["message"]?.firstOrNull() ?: ""
        val responseMessage = handleChat(userInput)
        return newFixedLengthResponse(Response.Status.OK, "application/json", """{"response": "$responseMessage"}""")
    }

    private fun handleChat(message: String): String {
        return "Echo: $message" // Placeholder response
    }
}
EOF

          # Create SettingsActivity.kt
          cat <<EOF > $GITHUB_WORKSPACE/LLMChatApp/app/src/main/java/com/example/llmchatapp/SettingsActivity.kt
package com.example.llmchatapp

import android.os.Bundle
import android.widget.Button
import androidx.appcompat.app.AppCompatActivity

class SettingsActivity : AppCompatActivity() {
    private lateinit var loadModelButton: Button
    private lateinit var deleteModelButton: Button
    private lateinit var combineModelsButton: Button

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_settings)

        loadModelButton = findView

android:id="@+id/loadModelButton"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Load Model" />

    <Button
        android:id="@+id/deleteModelButton"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Delete Model" />

    <Button
        android:id="@+id/combineModelsButton"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Combine Models" />
</LinearLayout>
EOF

          # Create the layout for MainActivity
          cat <<EOF > $GITHUB_WORKSPACE/LLMChatApp/app/src/main/res/layout/activity_main.xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <EditText
        android:id="@+id/messageInput"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="Type your message here"
        android:theme="@style/Theme.MaterialComponents" />

    <Button
        android:id="@+id/sendButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Send"
        android:theme="@style/Theme.MaterialComponents" />

    <TextView
        android:id="@+id/chatOutput"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="16dp" />

    <Button
        android:id="@+id/settingsButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Settings"
        android:layout_marginTop="16dp"
        android:theme="@style/Theme.MaterialComponents" />
</LinearLayout>
EOF

          # Create the layout for SettingsActivity
          cat <<EOF > $GITHUB_WORKSPACE/LLMChatApp/app/src/main/res/layout/activity_settings.xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="16dp">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Manage Models"
        android:textSize="24sp"
        android:paddingBottom="16dp" />

    <Button
        android:id="@+id/loadModelButton"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Load Model" />

    <Button
        android:id="@+id/deleteModelButton"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Delete Model" />

    <Button
        android:id="@+id/combineModelsButton"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Combine Models" />
</LinearLayout>
EOF

          # Create styles.xml for theming
          cat <<EOF > $GITHUB_WORKSPACE/LLMChatApp/app/src/main/res/values/styles.xml
<resources>
    <style name="AppTheme" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryVariant">@color/purple_700</item>
        <item name="colorOnPrimary">@android:color/white</item>
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorOnSecondary">@android:color/black</item>
    </style>
</resources>
EOF

          # Create colors.xml for theming
          cat <<EOF > $GITHUB_WORKSPACE/LLMChatApp/app/src/main/res/values/colors.xml
<resources>
    <color name="purple_500">#6200EE</color>
    <color name="purple_700">#3700B3</color>
    <color name="teal_200">#03DAC5</color>
</resources>
EOF

          # Create a settings.gradle file
          cat <<EOF > $GITHUB_WORKSPACE/LLMChatApp/settings.gradle
include ':app'
EOF

          # Change directory to app and create gradle wrapper
          cd $GITHUB_WORKSPACE/LLMChatApp || exit
          gradle wrapper --gradle-version 7.0

      - name: Build the project
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: llm-chat-app-apk
          path: app/build/outputs/apk/release/LLMChatApp-release.apk