name: Setup LoomChat

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        run: touch touch.txt
        run: pwd > touch.txt
      